# ...existing code...

# BMM Configuration
bmm:
  enable_validation: true
  strategy_alignment_threshold: 0.7
  policy_compliance_mode: "strict"
  objective_tracking: true
  
  # Default business context
  default_context:
    vision: "Build intelligent and autonomous AI systems"
    mission: "Provide flexible and powerful AI agent frameworks"
    core_values:
      - "Innovation"
      - "Reliability"
      - "Security"

  maturity_levels:
    1: "Initial BMM Implementation"
    2: "Managed BMM Process"
    3: "Defined BMM Architecture"
    4: "Quantitatively Managed BMM"
    5: "Optimizing BMM"
    
  directive_validation:
    policy_weight: 0.4
    rule_weight: 0.3
    goal_alignment_weight: 0.3
    minimum_compliance_score: 0.8
    
  assessment_configuration:
    swot_refresh_interval: 30  # days
    impact_threshold: 0.6
    confidence_threshold: 0.7

business_architect:
  evaluation_metrics:
    strategy_alignment_threshold: 0.8
    policy_compliance_threshold: 0.9
    objective_tracking_interval: 7  # days
  
  analysis_settings:
    swot_update_frequency: 30  # days
    context_evaluation_depth: "detailed"
    influencer_analysis_scope: "comprehensive"

mcp:
  enable_validation: true
  control_level: "moderate"
  safety_threshold: 0.8
  
  # Model control settings
  model_settings:
    gpt4:
      max_tokens: 8192
      temperature: 0.7
      top_p: 0.95
      rate_limit: 100
    llama2:
      max_tokens: 4096
      temperature: 0.8
      context_window: 4096
    codellama:
      max_tokens: 4096
      temperature: 0.5
      specialized_tasks: ["code_generation", "code_analysis"]
  
  # Safety controls
  safety_controls:
    content_filtering: 
      enabled: true
      threshold: 0.9
      blocked_categories: ["harmful", "malicious"]
    rate_limiting:
      enabled: true
      requests_per_minute: 50
      burst_limit: 100
    resource_monitoring:
      enabled: true
      max_memory_usage: "8GB"
      max_cpu_usage: 80
  
  # Access controls
  access_controls:
    enterprise:
      allowed_models: ["gpt-4", "claude-2"]
      restricted_actions: ["system_modification"]
      require_approval: true
      audit_logging: true
    
    development:
      allowed_models: ["gpt-3.5-turbo", "llama2"]
      restricted_actions: ["production_deployment"]
      require_approval: false